const palette = {
  bg: "#0A0A1F",
  bgDeep: "#06061A",
  surface: "#15152F",
  surfaceElevated: "#1E1E3F",
  border: "#2A2A55",
  primary: "#E63946",
  primaryDark: "#B92A38",
  gold: "#FFB300",
  goldDark: "#D48800",
  gem: "#3FD0FF",
  energy: "#7FFF6E",
  blue: "#5B5BFF",
  purple: "#8A4FFF",
  text: "#FFFFFF",
  textDim: "#B5B5D6",
  muted: "#6B6B8C",
  danger: "#FF4757",
  success: "#2ECC71",
};

const colors = {
  light: {
    text: palette.text,
    tint: palette.primary,
    background: palette.bg,
    foreground: palette.text,
    card: palette.surface,
    cardForeground: palette.text,
    primary: palette.primary,
    primaryForeground: palette.text,
    secondary: palette.surfaceElevated,
    secondaryForeground: palette.text,
    muted: palette.muted,
    mutedForeground: palette.textDim,
    accent: palette.gold,
    accentForeground: palette.bgDeep,
    destructive: palette.danger,
    destructiveForeground: palette.text,
    border: palette.border,
    input: palette.surfaceElevated,
  },
  dark: {
    text: palette.text,
    tint: palette.primary,
    background: palette.bg,
    foreground: palette.text,
    card: palette.surface,
    cardForeground: palette.text,
    primary: palette.primary,
    primaryForeground: palette.text,
    secondary: palette.surfaceElevated,
    secondaryForeground: palette.text,
    muted: palette.muted,
    mutedForeground: palette.textDim,
    accent: palette.gold,
    accentForeground: palette.bgDeep,
    destructive: palette.danger,
    destructiveForeground: palette.text,
    border: palette.border,
    input: palette.surfaceElevated,
  },
  radius: 16,
};

export const game = palette;
export default colors;
